### ISSUE TITLE
How to install cell map

### ISSUE THREAD

**Issue by izzud1655** [Rudloff/mls-cell-map#33]
Hi, sorry for noob question.
 I have problem how to setup this thing on localhost, I'm using windows 10, xampp & mysql. 

I don't know what it's mean and how to used here:
##Install
mkdir data
chmod -R 777 data
php import_data.php
bower install

Can anyone guide me step by step how to install mls-cell-map on localhost?
Thanks :)

**Comment by Rudloff** [comment]
These are [Bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) commands, you need to type them in a shell.
I think Windows 10 has a Bash shell but I don't use Windows so I can't rellay help you here.

**Comment by izzud1655** [comment]
Is there another way to install it wihout using bash commands?

**Comment by Rudloff** [comment]
Unfortunately no, it relies heavily on bash commands to download the data.
It might be possible to create a graphical installer but I don't really have the time right now.

**Comment by izzud1655** [comment]
Oh,ok..thank ya..I will try to explore how to install in windows..

**Comment by izzud1655** [comment]
**I have tried install  based on default instructions**
##Install
mkdir data
chmod -R 777 data
php import_data.php
bower install

**First problem, I got error message when run index.php.**
Server error!
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script. 

**Then, when I tried delete .htaccess file and reload again, it's show error as print screen below.So, how to fix them?
Thanks..**
<img src="http://simpana.cloudhub.my/img/temp/map.png"/>

**Comment by Rudloff** [comment]
It seems Leaflet.MakiMarkers 1.0 is not available anymore.
I updated it to 3.1 on the develop branch (c654e12440a7a01d6613be4c83c3fb141d9d0069).

@izzud1655 You can switch to the develop branch (are you using Git or downloading a release package?), then retry `bower update`.

**Comment by Rudloff** [comment]
As for the need to remove .htacces, it is probably because you don't have some Apache modules. So I added some conditions: 38a4fae04e1983ce49969a30d7626ebe4e9f13c7

**Comment by izzud1655** [comment]
I have been using Git for bower installation, then using Xampp Shell for execute mls-cell-map installation.
Thanks @Rudloff , I'm very grateful for your help,  I will try and respond soon.

**Comment by izzud1655** [comment]
**Sorry to trouble again, I have updated code and re-executed bower. So, it seems have improvement but still have some error as my screenshot below.**
disti directory is not found.
- http://localhost/map/dist/main.css
- http://localhost/map/dist/main.js
<img src="http://simpana.cloudhub.my/img/temp/map2.png"/>

**Comment by Rudloff** [comment]
You need to run [`grunt`](https://gruntjs.com/) in order to generate these files.
(Sorry, I forgot to add to the README: 59a0647e763d710e68f1ba59aa15bfab16064779)

**Comment by izzud1655** [comment]
**Ok @Rudloff , my maps is working right now. But have something is missing on my maps compared default demo, markers of LTE, UMTS, GSM, CDMA not appear.**
<img src="http://simpana.cloudhub.my/img/temp/map3.png"/>

**Comment by Rudloff** [comment]
It's probably that something went wrong during the import.
I made some changes to the import script.
Can you please pull the latest version of the `develop` branch and run `php import_data.php` again?

**Comment by izzud1655** [comment]
Ok @Rudloff , I'm trying to use [latest version of the develop branch](https://github.com/Rudloff/mls-cell-map/tree/c654e12440a7a01d6613be4c83c3fb141d9d0069) and will give you a feedback soon.

**Comment by izzud1655** [comment]
@Rudloff ,still have same problem,markers still not appear on map.
<img src="http://simpana.cloudhub.my/img/temp/map6.png"/>

Before that, I want to ask that I have 2 problems during installation process,maybe they cause my map is not working probably or not.

1- I have a warning during import data
<img src="http://simpana.cloudhub.my/img/temp/map4.png"/>

2- Then grunt-jslint not found. I have searched in grunt but not found to install it.
<img src="http://simpana.cloudhub.my/img/temp/map5.png"/>

**Comment by Rudloff** [comment]
1. It seems `local-infile` is disabled in your MySQL config. I made another change (525eaf6bc57934cfbe92ec65c0cbf193805d197e) that should fix that.
Can you please pull the latest version and try again?
2. You can safely ignore this warning. (But if you want to get rid of it, you just need to run `npm install` again.)

**Comment by izzud1655** [comment]
Ok @Rudloff , I will try soon, but before that I was forgot that have a problem also in grunt installation.
Like in screenshot below.

<img src="http://simpana.cloudhub.my/img/temp/map7.png"/>

**Comment by izzud1655** [comment]
@Rudloff ,I have used latest version,but problem is still same,coverage markers missing.:(

<img src="http://simpana.cloudhub.my/img/temp/map8.png"/>

**Comment by Rudloff** [comment]
Did `php import_data.php` output a warning this time ?
Does the `cells` table in your database contain any data?

If you can't make the import script work for you, you can import the `data/MLS-full-cell-export.csv` file in your database manually.
You have two ways to do that:
* With [phpMyAdmin](https://www.phpmyadmin.net/)'s import feature (you'll have to modify [some PHP settings](https://docs.phpmyadmin.net/en/latest/faq.html#faq1-16) since the file is quite big).
* By running something like this from MySQL's shell:
```sql
LOAD DATA LOCAL INFILE 'data/MLS-full-cell-export.csv' INTO TABLE `cells` FIELDS TERMINATED BY ',' IGNORE 1 LINES;
```

**Comment by izzud1655** [comment]
Sorry,I did not notice php import_data.php output a warning or not, but my cells table is empty.
But two others, cells_country and cell_mnc having data.

<img src="http://simpana.cloudhub.my/img/temp/phpadmin.png"/>

Thank @Rudloff , I will try solutions option.

**Comment by izzud1655** [comment]
Thank @Rudloff 
My maps is working fine now, I  have used MySQL's shell to query execute. 👍 

<img src="http://simpana.cloudhub.my/img/temp/map9.png"/>

**Comment by Rudloff** [comment]
Great news!
Thanks for your patience, we definitely need to improve error handling in the import script.
